### ISSUE TITLE
undefined method `pluralized_table_name' for ActiveRecord::Base:Class

### ISSUE THREAD

**Issue by aldavidson** [rgo/foreign_key_migrations#1]
Hi there

I'm trying to use script/generate foreign_key_migration in order to generate foreign keys for my db without wiping and recreating the whole thing

However, it crashes before doing anything with the error: undefined method `pluralized_table_name' for ActiveRecord::Base:Class

I know that pluralized_table_name is defined in redhillonrails_core, and i've checked that I have that plugin installed.

Do you have any ideas?

Thanks

**Comment by rgo** [comment]
Sorry for the delay, I was out for a while but I'm home again.
I don't have any idea but I'll try to check it this weekend.

**Comment by rgo** [comment]
I can not reproduce it in my system. I created a Rails application with 3 models then I executed "script/generate foreign_key_migration" and eventually rake db:migrate. None of these steps failed 

What rails version are you using?

**Comment by billsaysthis** [comment]
I'm using the original plugin. After migrating our app from Rails 2.3.5 to 2.3.10 I get this error as well but only when I run rake test:units.

**Comment by rgo** [comment]
Could you try automatic_foreign_key[1] ? 

Anyway I'll check as you said(updating from 2.3.5 to 2.3.10 and executing rake test:units).

[1] https://github.com/mlomnicki/automatic_foreign_key

**Comment by billsaysthis** [comment]
For the moment, at least, I can't switch. I did try just editing the plugin source to switch to the new version, pluralize_table_names, but got a wrong number of params error.

**Comment by aldavidson** [comment]
Hi,

Sorry I can't remember how I got round this! I would assume it was me being dumb and close the issue, but billsaysthis has had it as well.

Al
